# Introduction

The planet is facing a new source of pressure, a new challenge that is damaging all socio-ecological systems with the increase in the atmospheric concentration of greenhouse gases (GHGs) attributable to human activities, including deforestation and the misuse of fossil fuels. Successive reports of the Intergovernmental Panel on Climate Change (IPCC) (2013-2019-2021) are unequivocal on this subject. Indeed, they presented several evidences of the global warming trend, the melting of glaciers, the variation of precipitation patterns, the increase in the frequency or intensity of extreme events and the rise in sea level over the last decades and also demonstrated with fairly high confidence levels the influence of human activities in these climate imbalances.

In addition, they highlighted the negative impacts that climate variations cause on the most important socio-economic sectors of developed and developing countries, including the Least Developed Countries (LDCs) (IPCC, 2014).

While developed countries are showing signs of resilience to the effects of climate change, the situation is worrisome and even critical for LDCs and other developing countries, which, despite their low contribution to climate change, are among the most affected because of their weak response capacity.

Regardless of the GHG emission scenarios considered, all climate models predict an increase in global temperature over the next few decades at least. The 6th Assessment Report of the IPCC Working Group I "Climate Science and Physics" published in August 2021, projects a faster than expected temperature increase; it is expected to reach or even exceed the threshold of +1.5°C, the most ambitious objective of the Paris Agreement, around 2030, if urgent and drastic measures to reduce GHG emissions are not implemented (IPCC, 2021). Above 1.5°C, one of the high-risk consequences in West Africa is exposure to potentially deadly hot temperatures for more than 100 days per year (IPCC, 2021), which would exacerbate the disastrous consequences for the socio-economic development of all countries, particularly Burkina Faso whose economies are largely dependent on climate (Semde et al., 2021).

In the light of various scientific assessments, and given that climate change-related risks amplify development challenges for LDCs, countries Parties to the United Nations Framework Convention on Climate Change (UNFCCC) have recognized, through the Cancun Adaptation Framework and Decision 5/CP.17 adopted at COP17 in Durban, South Africa, reinforced by the Paris Agreement, the urgent need to develop and implement National Adaptation Plans (NAPs) has seen it as a means to facilitate effective adaptation planning in LDCs and other developing countries (LEG, 2012).

Two main objectives are pursued through the NAPs: (i) to reduce vulnerability to the impacts of climate change by building adaptive capacity, disaster risk reduction and resilience, and (ii) to coherently integrate climate change adaptation into relevant new or ongoing policies, programmes and work, in particular sustainable development planning processes and strategies, across relevant sectors and at different levels, as appropriate (UNFCCC, 2020).

It is in this context that Burkina Faso found it imperative to develop its NAP on the eve of COP 21 in 2015. This document constitutes the general framework of medium- and long-term actions for national efforts to adapt to climate change in the following sectors: (i) agriculture, (ii) livestock production, (iii) environment and natural resources, (iv) energy, (v) health, (vi) infrastructure and housing, (vii) women's associations, (viii) civil society organizations. As the deadline for the implementation of the first NAP is 5 years, the year 2021 should mark the beginning of a new phase, hence the justification for its revision. The revision process started with the evaluation in 2021 of the first NAP.

This NAP specifies a set of adaptation actions to be implemented over the next five years and will serve as a reference for any communal, regional and sectoral adaptation plans to climate change. It also describes the strategies to be prioritized to address the different priorities of adaptation, analysis and risk management and makes recommendations on the monitoring and evaluation framework that can feed into reporting under the enhanced transparency framework established by the Paris Agreement.

The methodological approach was participatory and iterative, taking into account adaptation priorities at the regional and municipal levels. First, a technical committee was set up to monitor, guide and ensure the quality of the deliverables and their validation. In addition, national and international experts were also mobilized for the production of basic documents such as the report on the evaluation of the first NAP, the vulnerability study in a pilot region, and climate projections. Finally, the deliverable produced was submitted to multi-stakeholder national validations to provide a consensus document.

This NAP document consists of four (4) parts structured as follows:

➢ The first part presents the national circumstances, takes stock of the implementation of the previous NAP, sets out the revision process and climate scenarios, analyses and identifies the gaps and shortcomings of the previous NAP, proposes palliative solutions, identifies new challenges and priorities, sets out the revision methodology based on the analysis of climate scenarios, identifying and assessing vulnerabilities by development sector to climate change;

➢ the second part sets out the guiding principles, vision and objectives of the NAP, assesses the costs and benefits of adaptation options, presents the methodology for integrating climate change adaptation into development policies and strategies and finally develops how to operationalize the NAP;

➢ the third part presents the implementation strategies envisaged for the NAP, highlighting the political and legal framework and institutional arrangements, the communication strategy adopted, the contribution of research and development and finally the strategy for mobilizing technical and financial resources. The country, in the innovation perspective of its revised NAP, has adopted the development of Regional Adaptation Plans (RAPs) to climate change, the main results of which for a region are presented in this section;

➢ the fourth part reports on the monitoring and evaluation and reporting framework on the implementation of the NAP as well as information on the process of its revision.
