# Monitoring, evaluation and reporting framework

This part of the NAP deals with monitoring and evaluation and is structured according to the following scheme:

➢ the importance of monitoring and evaluation;

➢ resources and capacities for monitoring and evaluation;

➢ monitoring and evaluation methodology;

➢ the monitoring, evaluation and reporting system;

➢ the review and update process;

➢ external evaluation.

## Importance of monitoring and evaluation

One of the main weaknesses often cited about the climate change policy framework in Burkina Faso is the lack of capitalization and evaluation of results or progress made. If there is no paradigm shift in this regard, the NAP risks being a mere policy document incapable of bringing about the transformations so desired by a large majority of the Burkinabe population. Thus, monitoring and evaluation and regular reporting on the implementation of national climate change adaptation strategies are of particular importance. In general, they make it possible to assess the effectiveness of the actions carried out on the level of vulnerability, the adaptive capacities or the resilience of the country. They are part of the dynamics of the transparency framework by promoting support, communication, learning, transparency and dialogue between stakeholders from different sectors in the implementation of the NAP.

## Resources and capacities for monitoring and evaluation

The resources and capacities necessary to ensure a good monitoring and evaluation of the NAP of Burkina Faso can be drawn from the following:

-   **Human resources:** the monitoring and evaluation unit within the SP/CNDD will be reinforced by at least three (3) additional people who will be responsible for processing the information collected from the Ministries and institutions concerned (local authorities, private sector and civil society) on climate change adaptation issues. However, staff capacity needs to be steadily strengthened to meet the challenges of the day.

-   **Technical resources:** The technical means to be acquired consist mainly of a manual and a monitoring and evaluation software, as well as computers. The design of the manual and the monitoring and evaluation software will be the responsibility of a consultant or a specialized firm. But until this is effective, a simple and practical methodology for the conduct of monitoring and evaluation is proposed below;

-   **Financial resources:** Financial resources need to be mobilized accordingly for the monitoring and evaluation system. In order to strengthen the capacity to mobilize in this direction, provision will be made for the levy of about 10% of the cost of each operational project of the NAP specifically for monitoring and evaluation.

The capacities of stakeholders will be strengthened, particularly in terms of vulnerability assessment, assessment of the impacts of climate change adaptation actions and improvement of national inter-institutional coordination mechanisms to enable the establishment of an appropriate and effective monitoring and evaluation system for the NAP as required by the enhanced transparency framework of the Paris Agreement.

## Monitoring and evaluation methodology

A methodology was used to assess the implementation of the first NAP, which has proven to be successful and could therefore be reused for future NAPs. This methodology is essentially based on the monitoring and evaluation of the NAP Performance Measurement Plan illustrated in Tables 30, 31 and 32 relating to the Global NAP Performance Measurement Plan. As a reminder, these tables give by strategic axis of the NAP, the specific objectives, the expected results, the performance indicators, the data sources, the method of data collection, the frequency of data collection and the data collectors.

The following are summary tables providing regular information on the progress of the NAP, which could be improved according to the situations in the annexes.

## NAP monitoring, evaluation and monitoring mechanism

In order to ensure a participatory, inclusive and iterative implementation of the NAP in Burkina Faso, a monitoring and evaluation mechanism will be put in place. This mechanism will ensure and improve the integration of the NAP into the planning and implementation of development policies, strategies and interventions in Burkina Faso. To this end, the monitoring and evaluation system includes:

-   **the monitoring and evaluation unit of the SP/CNDD:** it will be responsible for reporting on the status of implementation of the entire NAP and will be strengthened in terms of human, technical and financial resources. It will have to administer a database capable of informing the Government and all interested stakeholders on the measured performance of the NAP;

-   **M&E correspondents in the ministerial sectors covered by the NAP:** they will work in conjunction with the M&E unit of the SP/CNDD by feeding its database with information on the evolution of the NAP by sector. Accountability will be up to the regional level (designation of regional focal points);

-   **local authority stakeholders:** they will work on the integration, implementation, monitoring and evaluation of the NAP in each municipal development plan;

-   **private sector actors:** the mission of integration, implementation, monitoring and evaluation of the NAP is carried out by the Ministry in charge of the private sector, the Chamber of Commerce, Industry and Handicrafts of Burkina Faso and the Employers' Association; and

-   **civil society actors:** this mission is devolved to the national and regional umbrella bodies of NGOs/associations.

The monitoring and evaluation unit of the SP/CNDD as well as the monitoring and evaluation correspondents in the ministerial sectors covered by the NAP will produce periodic reports and communication documents on the evolution of the NAP for decision-makers and the general public. In order to make the system more effective, formal and, if possible, "binding" memoranda of understanding will be drawn up between the institutions concerned, which will have to designate focal points who will be equipped to do so. In order to standardize the M&E and Reporting system, a reference document will be defined, inter alia, on the data to be collected, the methods of collection, the frequency of collection, the processing to be carried out and the templates to be used for reporting. The data to be collected will be guided by both the objectives pursued in the actions envisaged and the reporting obligations under the UNFCCC and the Paris Agreement.

## Review and update process

The phenomenon of climate change is dynamic and the effects are constantly changing in time and space. This means that the NAP should not be set in stone, but rather should be updated and updated after a certain period of implementation. The revision of the NAP may take place under the following conditions: (i) when new information or vulnerability analyses are made; (ii) when there are developments in international climate negotiations; and (iii) where national circumstances so require.

The data and information collected will be used to produce semi-annual and annual reports. The reports will be tailored to the needs and capabilities of the recipients. The frequency and timing of the production of business outcomes will be defined to ensure that data and information are used to inform the development or revision of policies, strategies and interventions.

## External evaluation

In order to achieve transparency, it is recommended to carry out independent external evaluations. There are three types of evaluation:

1)  a mid-term evaluation focusing on the effectiveness and efficiency of the actions of the five-year NAP action plan;

2)  a final evaluation at the end of the five (5) years of implementation in order to assess the results achieved. This assessment will allow for reframing for the next five-year NAP action plan;

3)  a retrospective evaluation to measure impacts, lessons learned, and sustainability of results.

The value of such an evaluation is also to provide a useful basis for the development of future policies and strategies. It can be completed two or more years after the end of the previous five-year NAP action plan.

The proposed monitoring and evaluation system, even if it aims to report on the functioning and results of the NAP, will be part of the MRV framework under construction at the SP/CNDD and consolidate it.
