# Conclusion

The contribution to the global effort to limit GHG emissions to 1.5°C by 2100 and the need to strengthen the resilience of communities, systems and means of production of States have led the United Nations to resolve to support them in equipping themselves with planning tools that integrate climate change into development actions. Burkina Faso, a poor country that is highly vulnerable to climatic hazards, is not to be outdone by this dynamic. The country has benefited from the implementation of actions to adapt to the adverse effects of climate change in its priority sectors and emergencies through the NAPAs in 2007 and has projected itself into the medium and long term with the NAP adopted in 2015. The implementation of this strategy has produced its effects in terms of the acquisition of eco-citizen behaviours, the reconstitution of vegetation cover and the acquisition of tools and resilience measures by the population. However, the evaluation of this implementation reveals shortcomings that tend to hinder the efforts made.

After five (5) years of implementation, the evolution of the socio-economic and political context calls for the revision of this document with a view to reviewing the guidelines with a view to adapting them to the current context.

In addition to traditional climate risks (droughts and floods), this NAP includes extreme heat, which has become a major climate risk. Climate vulnerability studies are therefore based on these risks in the Burkinabe context.

This NAP benefited from vulnerability data generated by newer, more performant models. In addition, it has the particularity of integrating the notion of Regional Adaptation Plan (PRA).

All these vulnerability studies carried out as part of the formulation of the ARPs also indicated that forests and natural resources, energy, agriculture, animal and fisheries resources, health, infrastructure and housing, are the sectors most sensitive to climate change in the medium and long term.

Despite this state of vulnerability and unfavourable natural conditions, solutions exist to enable Burkina Faso to move towards sustainable development. To achieve this, policymakers should place climate change adaptation at the heart of development policies and strategies.

Based on the scientific investigations carried out, it appears that adaptation measures, although costly, will make it possible to reap many benefits for the development of Burkina Faso, the main ones being: (i) strengthening the resilience of agriculture and ecosystems; (ii) securing pastoral activities and sustainable development of the pastoral economy; (iii) greenhouse gas mitigation; (iv) the best health protection of the population; and (v) women's improved access to natural resources and decision-making spaces.

The expected socio-economic benefits of the implementation of the NAP are: (i) an increase in production and incomes of rural populations; (ii) a strong contribution to GDP; (iii) the creation of decent green jobs; and (iv) spillover effects for the rest of the economy.

The implementation of these actions requires both considerable financial and human resources as well as appropriate and effective institutional arrangements to ensure not only their implementation, but also for the performance of monitoring and evaluation and reporting.

Responses to the expected adverse effects of climate change will require increased mobilization of actors at all levels. The objectives set for this mobilization are, among others, (i) to make available human resources related to climate change for each sector considered, (ii) to strengthen the capacities of the main actors and (iii) to provide responses to the adaptation costs assessed for these vulnerable sectors in the medium and long term.

To this end, strong actions deserve to be undertaken and carried out by Burkina Faso, including:

-   the adoption and implementation of a national climate change committee to monitor the implementation of the NAP;

-   strengthening synergies between stakeholders in the field of climate change (researchers, government technical services, producers, the private sector, NGOs and associations, etc.);

-   strengthening training and awareness-raising activities for populations on the implications of climate change for their livelihoods and livelihoods;

-   periodic meetings between the State and its various partners for the operationalization of this NAP;

-   the establishment of a Monitoring Committee for the implementation of the NAP in line with the transparency framework under construction.

The overall budget for the implementation of the NAP for the five (5) year implementation period is estimated at: **Two hundred and eleven billion two hundred and thirty-three million eight hundred and seventy-nine thousand nine hundred and twenty-four (211,233,879,924) CFA francs**, of which **two hundred and eleven billion two hundred and six hundred and fifty-nine thousand eight hundred and ninety-eight (211,206,259,898) CFA francs** will be financed by the State, **twenty-four million nine hundred and sixty-one thousand five hundred (24,961,500 FCFA)** addressed to partners and the **remainder two thousand six hundred and fifty-eight thousand eighty (2,658,080 FCFA)** is to be sought.

The NAP, as a document for planning actions to adapt to climate change and mobilize resources, will make it possible, in the medium and long term, to address the challenges identified.


