# Bibliography {.unnumbered}

Africa RiskView. (2020). END OF SEASON REPORT \| BURKINA FASO (2020). <https://www.arc.int/sites/default/files/2021-10/BF_RapportFinDeSaison_2020_FR.pdf>

Africa RiskView. (2020). END OF SEASON REPORT \| BURKINA FASO (2020). <https://www.arc.int/sites/default/files/2021-10/BF_RapportFinDeSaison_2020_FR.pdf>

Arias, P. A., Bellouin, N., Coppola, E., Jones, R. G., Krinner, G., Marotzke, J., Naik, V., Palmer, M. D., Plattner, G.-K., Rogelj, J., & others. (2021). Technical summary. Climate Change, 33–144.

Arisco, N. J., Sewe, M. O., Bärnighausen, T., Sié, A., Zabre, P., & Bunker, A. (2023). The effect of extreme temperature and precipitation on cause-specific deaths in rural Burkina Faso: a longitudinal study. The Lancet Planetary Health, 7(6), e478–e489. [https://doi.org/10.1016/S2542-5196(23)00027-X](https://doi.org/10.1016/S2542-5196(23)00027-X){.uri}

AfDB, 2015. Addressing Fragility and Building Resilience in Africa: The African Development Bank Group's Strategy 2014–2019. Abidjan: African Development Bank, 61 p. <https://www.afdb.org/fileadmin/uploads/afdb/Documents/Policy-Documents/Addressing_Fragility_and_Building_Resilience_in_Africa-_The_AfDB_Group_Strategy_2014%E2%80%932019.pdf>

World Bank, 2013. Climate Change: What Are the Consequences for Africa, Asia and Poor Coastal Communities? <https://www.banquemondiale.org>.

CONASUR, 2012. National Multi-Hazard Disaster Preparedness and Response Plan. <https://www.preventionweb.net/publication/burkina-faso-plan-national-multi-risques-de-preparation-et-de-reponse-aux-catastrophes>

United Nations Framework Convention on Climate Change (UNFCCC), 2010. Climate Change, Agriculture and Food Security. Working Paper No. 2, 12p.

FAO, 2015. Synthesis Report of the National Agricultural Risk Profile in Burkina Faso

Fischer, E. M., Sedláček, J., Hawkins, E., & Knutti, R. (2014). Models agree on forced response pattern of precipitation and temperature extremes. Geophysical Research Letters, 41(23), 8554–8562. <https://doi.org/10.1002/2014GL062018>

Frank Sperling et al., 2003. Poverty and Climate Change. Reducing the vulnerability of the poor through adaptation. Prepared by: African Development Bank; Asian Development Bank; World Bank; Department for International Development, United Kingdom; Directorate-General for Development

Stern, R. D., Dennett, M. D., & Garbutt, D. J. (1981). The start of the rains in West Africa. Journal of Climatology, 1(1), 59–68. <https://doi.org/10.1002/joc.3370010107>

IPCC, 2001. IPCC (Intergovernmental Panel on Climate Change) Comprehensive Assessment Report. www.developpement-durable.gouv.fr/giec

IPCC, 2007. Climate Change Stocktaking. Contribution of Working Groups I, II and III to the Fourth Assessment Report of the Intergovernmental Panel on Climate Change, 103 p.; www.developpement-durable.gouv.fr/giec

IPCC, 2013. The science. Contribution of Working Group I to the Fifth Assessment Report of the Intergovernmental Panel on Climate Change. Summary for Policymakers. www.developpement-durable.gouv.fr/giec

IPCC, 2014: Climate Change 2014: Impacts, Adaptation and Vulnerability Abstracts, Frequently Asked Questions and Thematic Inserts. Contribution of Working Group II to the Fifth Assessment Report of the Intergovernmental Panel on Climate Change. www.developpement-durable.gouv.fr/giec

IPCC, 2019. IPCC Special Report on Climate Change and Land Use. <https://climat.be/changements-climatiques/changements-observes/rapports-du-giec/2019-> rapport-special-sur-l-utilisation-des-sols

IPCC, 2021. The physical scientific basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.

Harris, N.L., Gibbs, D.A., Baccini, A. et al. Global maps of twenty-first century forest carbon fluxes. Nat. Clim. Chang. 11, 234–240 (2021). <https://doi.org/10.1038/s41558-020-00976-6>

Houghton, J. T., Ding, Y., Griggs, D. J., Noguer, M., Van der Linden, P. J., Dai, X., Maskell, K., & Johnson, C. A. (2001). Contribution of working group I to the third assessment report of the intergovernmental panel on climate change. Climate Change 2001: The Scientific Basis, 388.

Ibrahim, B., Karambiri, H., Polcher, J., Yacouba, H., & Ribstein, P. (2014). Changes in rainfall regime over Burkina Faso under the climate change conditions simulated by 5 regional climate models. Climate Dynamics, 42(5–6), 1363–1381. <https://doi.org/10.1007/s00382-013-1837-2>

Idrissa Semde, Samuel Yonkeu, Mathieu Badolo, Samuel Paré, Neya Tiga. 2021, Enhancing Food Security and Disaster Risk Resilience in Burkina Faso: New Resilience Pathways to Disaster Risk and Food Security in the Sahel for Public Action; IOSR Journal of Environmental Science, Toxicology and Food Technology (IOSR-JESTFT) e-ISSN: 2319-2402, p- ISSN: 2319-2399.Volume 15, Issue 6 ser. I (June 2021), PP 39-50 www.iosrjournals.org

INSD; 2020. Statistical Yearbook 2020. 5th General Population and Housing Census.

IRENA. (2021). SUITABLE AREAS FOR UTILITY-SCALE SOLAR AND WIND ENERGY. <https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2021/Sep/IRENA_utility_solar_wind_Burkina_Faso_2021_FR.pdf>

Issuu, 2022. Private Sector & Development n°38 - Adaptation to climate change. <https://issuu.com/objectif-developpement/docs/pro-revue_n_38-fr-page>

Jonas Wanvoeke, Jean-Philippe Venot, Charlotte De Fraiture & Margreet Zwarteveen (2016) Smallholder Drip Irrigation in Burkina Faso: The Role of Development Brokers, The Journal of Development Studies, 52:7, 1019-1033, DOI: 10.1080/00220388.2015.1107048

Jones, B., O'Neill, B. C., McDaniel, L., McGinnis, S., Mearns, L. O., & Tebaldi, C. (2015). Future population exposure to US heat extremes.Nature Climate Change,5(7), 652–655.https://doi.org/10.1038/nclimate2631

Jones, B., O'Neill, B. C., McDaniel, L., McGinnis, S., Mearns, L. O., & Tebaldi, C. (2015). Future population exposure to US heat extremes. Nature Climate Change, 5(7), 652–655. <https://doi.org/10.1038/nclimate2631>

K.C., S., & Lutz, W. (2017). The human core of the shared socioeconomic pathways: Population scenarios by age, sex and level of education for all countries to 2100. Global Environmental Change, 42, 181–192. <https://doi.org/10.1016/j.gloenvcha.2014.06.004>

LAME, 2012. Elaboration of the Programmatic NAPA of Burkina Faso. Multisectoral vulnerability analysis for the formulation of a medium- and long-term national climate change adaptation strategy for Burkina Faso by 2025 and 2050. Laboratory of Mathematical Analysis of Equations (LAME) Training and Research Unit in Exact and Applied Sciences, University of Ouagadougou.

Maula, H., Hongisto, V., Östman, L., Haapakangas, A., Koskela, H., & Hyönä, J. (2016). The effect of slightly warm temperature on work performance and comfort in open-plan offices-a laboratory study. Indoor Air, 26(2), 286–297.

MEF, 2016. National Economic and Social Development Plan (PNDES 2016-2020), 87p. www.finances.gov.bf/index.php?option=com_content&view=article&id=2.

MERH, 2015. National Climate Change Adaptation Plan (NAP, 2015). www.data.gov.bf

OECD, 2020. Statement by the OECD Secretary-General on climate finance trends up to 2020. <https://www.oecd.org/fr/presse/declaration-du-secretaire-general-de-l-ocde-sur-les-tendances-du-financement-climatique-observees-jusqu-en-2020.htm>. <https://www.oecd.org/fr/env/cc/36214804.pdf>

Omotosho, J. B., Balogun, A. A., & Ogunjobi, K. (2000). Predicting monthly and seasonal rainfall, onset and cessation of the rainy season in West Africa using only surface data. International Journal of Climatology, 20(8), 865–880. [https://doi.org/10.1002/1097-0088(20000630)20:8](https://doi.org/10.1002/1097-0088(20000630)20:8){.uri}\<865::AID-JOC505\>3.0.CO; 2-R

Ouedraogo, B. I., Levermore, G. J., & Parkinson, J. B. (2012). Future energy demand for public buildings in the context of climate change for Burkina Faso. Building and Environment, 49, 270–282. <https://doi.org/10.1016/j.buildenv.2011.10.003>

WFP, 2012. The Cost of HUNGER in Burkina Faso: The Social and Economic Impact of Child Undernutrition in Burkina Faso. Report by the United Nations Economic Commission for Africa (ECA) and the World Food Programme.

Paris, 2015. Adoption of the Paris Agreement Proposal by the President, 21932 (December), 1–32. <https://unfccc.int/sites/default/files/english_paris_agreement.pdf>

UNDP, 2020. Human Development Report 2016. www.undp.org

Riahi, K., van Vuuren, D. P., Kriegler, E., Edmonds, J., O'Neill, B. C., Fujimori, S., Bauer, N., Calvin, K., Dellink, R., Fricko, O., Lutz, W., Popp, A., Cuaresma, J. C., KC, S., Leimbach, M., Jiang, L., Kram, T., Rao, S., Emmerling, J., ... Tavoni, M. (2017). The Shared Socioeconomic Pathways and their energy, land use, and greenhouse gas emissions implications: An overview. Global Environmental Change, 42, 153–168. <https://doi.org/10.1016/j.gloenvcha.2016.05.009>

Rothfusz, L. P., & Headquarters, N. W. S. S. R. (1990). The heat index equation (or, more than you ever wanted to know about heat index). Fort Worth, Texas: National Oceanic and Atmospheric Administration, National Weather Service, Office of Meteorology, 9023.

Sawadogo, W., Abiodun, B. J., & Okogbue, E. C. (2019). Impact of global warming on photovoltaic power generation over West Africa. Renewable Energy. <https://doi.org/https://doi.org/10.1016/j.renene.2019.11.032>

Serpantié Georges, Dorée Augustine, Fusillier Jean-Louis, Moity Maizi Pascale, Lidon Bruno, Douanio Manaka, Sawadogo Abdraime, Bossa Aymar Yaovi, Hounkpé Jean. 2019. New risks in the lowlands of Sudanese terroirs. A case study in Burkina Faso. Cahiers Agricultures, 28:19, 10 p. <https://doi.org/10.1051/cagri/2019020>

Shi, L., Liu, P., Kloog, I., Lee, M., Kosheleva, A., & Schwartz, J. (2016). Estimating daily air temperature across the Southeastern United States using high-resolution satellite data: A statistical modeling study. Environmental Research, 146, 51–58. <https://doi.org/10.1016/j.envres.2015.12.006>

Sorghum, R., Jungmann, M., Souares, A., Danquah, I., & Sauerborn, R. (2021). Climate Change, Health Risks, and Vulnerabilities in Burkina Faso: A Qualitative Study on the Perceptions of National Policymakers. International Journal of Environmental Research and Public Health, 18(9), 4972. <https://doi.org/10.3390/ijerph18094972>

SP/CNDD, 2016. Report on the State of the Environment in Burkina Faso. Version 4, (REEB4) 238 pp. <http://www.onedd-burkina.info/>.

SP/CNDD, 2023. Regional Climate Change Adaptation Plan 2024-2028

SP/CONEDD, 2013. National Action Plan for Adaptation to Vulnerability and Climate Change (PANA), 32p. <https://www.weadapt.org/organisation/spconedd>.

Thrasher, B., Wang, W., Michaelis, A., Melton, F., Lee, T., & Nemani, R. (2022). NASA Global Daily Downscaled Projections, CMIP6. Scientific Data, 9(1), 262. <https://doi.org/10.1038/s41597-022-01393-4>

Thrasher, B., Wang, W., Michaelis, A., Melton, F., Lee, T., & Nemani, R. (2022). NASA Global Daily Downscaled Projections, CMIP6. Scientific Data, 9(1), 262. <https://doi.org/10.1038/s41597-022-01393-4>

